### ISSUE TITLE
not possible to input data.frame

### ISSUE THREAD

**Issue by jgn301** [ChristianGoueguel/HotellingEllipse#2]
Hi Christian, 

both the `ellipseCoord` and the `ellipseParam`  function contain the following expression:
` if (is.data.frame(data) == FALSE | tibble::is_tibble(data) == FALSE) {
    stop("Data must be of class data.frame, tbl_df, or tbl")
  }`
If `data` is a "normal" `data.frame`, the if expression will evaluate to `TRUE` and execution will be stopped. I think the `|` should be changed to a `&` to also allow data.frames as input. 

Regards

**Comment by ChristianGoueguel** [comment]
@jgn301, thanks for pointing this out. I will check it as soon as possible.

**Comment by ChristianGoueguel** [comment]
As pointed out by @jgn301, an error occurs in the `ellipseParam` and `ellipseCoord` functions, when data is `data.frame`, instead of `tibble`. As for now, the issue has been resolved in the development version of the package.

**Comment by bryanhanson** [comment]
Can the development version be submitted to CRAN please?  Would like to use in production.

**Comment by ChristianGoueguel** [comment]
@bryanhanson, it should be done this week.
